[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.96

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 18

[colors.cursor]
cursor = "#f5e0dc"

[colors.primary]
background = "#1e1e2e"
foreground = "#a9b1d6"

[colors.normal]
black = "#363b54"
blue = "#7199ee"
cyan = "#38a89d"
green = "#98c379"
magenta = "#a485dd"
red = "#ee6d85"
white = "#A0A8CD"
yellow = "#d7a65f"

[colors.bright]
black = "#363b54"
blue = "#7199ee"
cyan = "#38a89d"
green = "#98c379"
magenta = "#a485dd"
red = "#ee6d85"
white = "#A0A8CD"
yellow = "#d7a65f"
