#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# install custom config
# mkdir -p ~/.config/nvim/lua/custom
# cp -a ./nvim/lua/custom/. ~/.config/nvim/lua/custom

mkdir -p "$HOME/.config/nvim"
ln -fs "$SCRIPT_DIR/nvim/init.lua" "$HOME/.config/nvim/init.lua"
ln -fs "$SCRIPT_DIR/nvim/lua" "$HOME/.config/nvim/lua"

cp -R "$SCRIPT_DIR/.warp/" "$HOME/.warp/"
