#!/usr/bin/env bash

# install nvim first
./install_nvim

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# copy dotfiles
dotfiles=(
  '.zshrc'
  '.aliases'
  '.spaceship_profile'
  '.devvars'
)

for f in "${dotfiles[@]}"
do
  echo "$f"
  rm -rf "$HOME/$f"
  ln -s "$SCRIPT_DIR/$f" "$HOME/$f"
done

# install spaceship theme
rm -rf "$HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
ln -s "$SCRIPT_DIR/spaceship.zsh-theme" "$HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
