#!/usr/bin/env bash

# if NvChad not installed, install it
[ ! -d "$HOME/.config/nvim" ] && (git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim)

# install custom config
mkdir -p ~/.config/nvim/lua/custom
cp -a ./nvim/lua/custom/. ~/.config/nvim/lua/custom

