#!/usr/bin/env bash

mkdir -p ~/.config/nvim/plug
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/lua/own

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

for f in `find -E . -regex ".*\.vim$|.*\.lua$"`; do
  echo $f
  rm -rf ~/.config/nvim/$f
  ln -s $SCRIPT_DIR/$f ~/.config/nvim/$f
done
