local M = {}

-- stylua: ignore
M.icons = {
    dap = {
        Stopped             = { ">", "DiagnosticWarn", "DapStoppedLine" },
        Breakpoint          = "B",
        BreakpointCondition = "C",
        BreakpointRejected  = { "R", "DiagnosticError" },
        LogPoint            = "L",
    },
    git = {
        added    = "+",
        modified = "~",
        removed  = "-",
    },
    lsp = {
        default       = " ",
        biome         = "󰯯 ",
        copilot       = " ",
        lua_ls        = "󰢱 ",
        clangd        = "󰢱 ",
        eslint        = "󰱺 ",
        jsonls        = " ",
        marksman      = " ",
        tailwindcss   = "󱏿 ",
        vtsls         = "󰛦 ",
        zls           = " ",
    },
    kinds = {
        Array         = " ",
        Boolean       = "󰨙 ",
        Class         = " ",
        Codeium       = "󰘦 ",
        Color         = " ",
        Control       = " ",
        Collapsed     = " ",
        Constant      = "󰏿 ",
        Constructor   = " ",
        Copilot       = " ",
        Enum          = " ",
        EnumMember    = " ",
        Event         = " ",
        Field         = " ",
        File          = " ",
        Folder        = " ",
        Function      = "󰊕 ",
        Interface     = " ",
        Key           = " ",
        Keyword       = " ",
        Method        = "󰊕 ",
        Module        = " ",
        Namespace     = "󰦮 ",
        Null          = " ",
        Number        = "󰎠 ",
        Object        = " ",
        Operator      = " ",
        Package       = " ",
        Property      = " ",
        Reference     = " ",
        Snippet       = "󱄽 ",
        String        = " ",
        Struct        = "󰆼 ",
        Supermaven    = " ",
        TabNine       = "󰏚 ",
        Text          = " ",
        TypeParameter = " ",
        Unit          = " ",
        Value         = " ",
        Variable      = "󰫧 ",
    },
}

return M
