local M = {}

M.icons = {
    misc = {
        dots = "󰇘",
    },
    ft = {
        octo = "",
    },
    dap = {
        Stopped             = { ">", "DiagnosticWarn", "DapStoppedLine" },
        Breakpoint          = "B",
        BreakpointCondition = "C",
        BreakpointRejected  = { "R", "DiagnosticError" },
        LogPoint            = "L",
    },
    diagnostics = {
        Error = "E ",
        Warn  = "W ",
        Hint  = "H ",
        Info  = "I ",
    },
    git = {
        added    = "+",
        modified = "~",
        removed  = "-",
    },
    kinds = {
        Array         = " ",
        Boolean       = "󰨙 ",
        Class         = " ",
        Codeium       = "󰘦 ",
        Color         = " ",
        Control       = " ",
        Collapsed     = " ",
        Constant      = "󰏿 ",
        Constructor   = " ",
        Copilot       = " ",
        Enum          = " ",
        EnumMember    = " ",
        Event         = " ",
        Field         = " ",
        File          = " ",
        Folder        = " ",
        Function      = "󰊕 ",
        Interface     = " ",
        Key           = " ",
        Keyword       = " ",
        Method        = "󰊕 ",
        Module        = " ",
        Namespace     = "󰦮 ",
        Null          = " ",
        Number        = "󰎠 ",
        Object        = " ",
        Operator      = " ",
        Package       = " ",
        Property      = " ",
        Reference     = " ",
        Snippet       = "󱄽 ",
        String        = " ",
        Struct        = "󰆼 ",
        Supermaven    = " ",
        TabNine       = "󰏚 ",
        Text          = " ",
        TypeParameter = " ",
        Unit          = " ",
        Value         = " ",
        Variable      = "󰫧 ",
    },
}

return M
